version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-uploader"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1angxchzuq7t0"
s3_prefix = "s3-uploader"
region = "ap-northeast-2"
profile = "happy-athumb"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoUserPoolDomainParameter=\"upload-user-pool\""
image_repositories = []
